name: app_v2ray_manager
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_v2ray: ^1.0.10
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  file_picker: ^10.0.0
  fl_chart: ^1.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.6
  installed_apps: 1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

